DROP DATABASE IF EXISTS qna;

CREATE DATABASE qna;

\c qna;

CREATE TABLE IF NOT EXISTS questions (
  id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  product_id varchar(15),
  body text,
  date_written text,
  asker_name varchar(50),
  asker_email varchar(255),
  reported boolean,
  helpful varchar(15)
);

COPY questions
FROM '/Users/mtanaka/HackReactor/SDC_data/questions.csv'
DELIMITER ','
CSV HEADER;

ALTER TABLE questions
RENAME COLUMN id TO question_id;

ALTER TABLE questions
RENAME COLUMN body TO question_body;

ALTER TABLE questions
RENAME COLUMN date_written TO question_date;

ALTER TABLE questions
RENAME COLUMN helpful TO question_helpfulness;


CREATE TABLE IF NOT EXISTS answers (
  id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  question_id int,
  body text,
  date_written text,
  answerer_name varchar(50),
  answerer_email varchar(255),
  reported boolean,
  helpful varchar(15),
  FOREIGN KEY (question_id) REFERENCES questions (id)
);

COPY answers
FROM '/Users/mtanaka/HackReactor/SDC_data/answers.csv'
DELIMITER ','
CSV HEADER;

ALTER TABLE answers
RENAME COLUMN id TO answer_id;

ALTER TABLE answers
RENAME COLUMN date_written TO date;

ALTER TABLE answers
RENAME COLUMN helpful TO helpfulness;

CREATE TABLE IF NOT EXISTS answers_photos (
  id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  answer_id int,
  photo_url text,
  FOREIGN KEY (answer_id) REFERENCES answers (id)
);

COPY answers_photos
FROM '/Users/mtanaka/HackReactor/SDC_data/answers_photos.csv'
DELIMITER ','
CSV HEADER;

ALTER TABLE answers_photos
RENAME COLUMN photo_url TO url;

SELECT


-- SELECT questions.question_id, question_body, answers.question_id, body FROM questions INNER JOIN answers ON questions.question_id = answers.question_id;

-- Working SELECT query to include custon column 'test_vale' with value of 'hi there':
-- SELECT questions.question_id, question_body, product_id, answers.question_id, body, 'hi there' as test_value FROM questions, answers WHERE questions.question_id = answers.question_id AND product_id='4';